#define MODE_POS 0
#define MODE_DISABLED 0
#define MODE_EVENT 1
#define MODE_TASK 3

#define PSEL_POS 8

#define POLARITY_POS 16
#define POLARITY_NONE 0
#define POLARITY_LOTOHI 1
#define POLARITY_HITOLO 2
#define POLARITY_TOGGLE 3

#define OUTINIT_POS 20
#define OUTINIT_LOW 0
#define OUTINIT_HIGH 1

// Example: NRF_GPIOTE->CONFIG[0] = MODE_EVENT | BUCKLER_BUTTON0 << PSEL_POS | POLARITY_HITOLO << POLARITY_POS
